# Generated by Django 4.0.3 on 2022-04-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApi', '0002_alter_tasks_options_tasks_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='Responsible',
        ),
    ]
