# Generated by Django 4.0.3 on 2022-04-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApi', '0003_remove_tasks_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='SrcAvatar',
        ),
    ]
