# Generated by Django 4.0.3 on 2022-04-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApi', '0004_remove_tasks_srcavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='StageOfExecution',
            field=models.CharField(choices=[(1, 'Задачи'), (2, 'В работе'), (3, 'Тестирование'), (4, 'Завершенные')], max_length=20, verbose_name='Стадия'),
        ),
    ]
