# Generated by Django 4.0.3 on 2022-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApi', '0005_alter_tasks_stageofexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='StageOfExecution',
            field=models.CharField(choices=[('Задачи', 'Задачи'), ('В работе', 'Вработе'), ('Тестирование', 'Тестирование'), ('Завершенные', 'Завершенные')], max_length=20, verbose_name='Стадия'),
        ),
    ]
