# Generated by Django 4.0.3 on 2022-04-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApi', '0009_delete_assistingintheexecution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='EndTime',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='StageOfExecution',
            new_name='stageOfExecution',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='StartTime',
            new_name='startTime',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Task',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Responsible',
            new_name='user',
        ),
    ]
